server:
  port: 8080
  servlet:
    context-path: /springboot
#    session:
#      timeout: 60
  tomcat:
    max-threads: 250
    uri-encoding: utf-8
    basedir: c:/spring-boot-tomcat-tmp
    accesslog:
      enabled: true

logging:
  path: c:/spring-boot-tomcat-tmp
  file: spring-boot-app.log



spring:
  mvc:
    static-path-pattern: /static/**     # 静态文件位置

  thymeleaf:
    cache: false                        #1) 关闭模板引擎的缓存，开发环境使用，生产环境改为true
    prefix: classpath:/templates/thymeleaf/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html

  devtools:
    restart:
      enabled: true                     #2) 热部署生效
      additional-paths: src/main/java   #3) 监听目录

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1/db_spring_boot?useUnicode=true&characterEncoding=utf8&serverTimezone=PRC
    username: root
    password: 123456


#  freemarker:
#    template-loader-path: classpath:/templates    #模板路径
#    cache: false                                  #不缓存，即时刷新，生产环境为 true
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .ftl


