server:
  port: 8080
  servlet:
    context-path: /springboot
    session:
      timeout: 60m
  tomcat:
    max-threads: 250
    uri-encoding: utf-8
    basedir: c:/spring-boot-tomcat-tmp
    accesslog:
      enabled: true

logging:
  path: c:/spring-boot-tomcat-tmp
  file: spring-boot-app.log
  # 该包下所有日志在 error 流输出
#  level:
#    com.bwf.springboot.mapper: error

#在使用 DevTools 时，通用Mapper经常会出现 class x.x.A cannot be cast to x.x.A。
#同一个类如果使用了不同的类加载器，就会产生这样的错误，
#所以解决方案就是让通用Mapper和实体类使用相同的类加载器即可。
#DevTools 默认会对 IDE 中引入的所有项目使用 restart 类加载器，
#  对于引入的 jar 包使用 base 类加载器，
#  因此只要保证通用Mapper的jar包使用 restart 类加载器即可。
restart:
  include:
    mapper: /mapper-[\\w-\\.]+jar
    pagehelper: /pagehelper-[\\w-\\.]+jar


# mybatis 相关设置
mybatis:
  type-aliases-package: com.bwf.springboot.model
  mapper-locations: classpath:mapper/*.xml

mapper:
  mappers: com.bwf.springboot.mapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

spring:
  mvc:
    static-path-pattern: /static/**     # 静态文件位置

  servlet:
    multipart:
      enabled: true                     # 开启文件上传
      file-size-threshold: 0MB            # 大于0的文件写入磁盘
      location: c:/tmp_files            # 临时目录
      max-file-size: 10MB                # 单个文件上限
      max-request-size: 50MB             # 单次请求上限


  messages:                             # i18n配置
    basename: i18n/messages             # 配置文件位置
    encoding: utf-8
    cache-duration: 60m

  freemarker:
    template-loader-path: classpath:/templates    #模板路径
    cache: false                                  #不缓存，即时刷新，生产环境为 true
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl

  thymeleaf:
    cache: false                        #1) 关闭模板引擎的缓存，开发环境使用，生产环境改为true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html

  devtools:
    restart:
      enabled: true                     #2) 热部署生效
      additional-paths: src/main/java   #3) 监听目录

  #  jpa:
  #    hibernate:
  #      ddl-auto: update
  #    show-sql: true

  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 1000
        max-wait: -1s
        max-idle: 10
        min-idle: 2
    timeout: 0s

  datasource:
    #  使用 alibaba druid 数据源
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/db_spring_boot?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=PRC
      username: root
      password: 123456


#    使用 jpa 数据源
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1/db_spring_boot?useSSL=true&useUnicode=true&characterEncoding=utf8&serverTimezone=PRC
#    username: root
#    password: 123456









