package com.bwf.springboot.mapper;

import com.bwf.springboot.model.User;

import java.util.List;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Aug 29 19:55:18 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Wed Aug 29 19:55:18 CST 2018
     */
    List<User> selectAll();
}